---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  #always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-7.3

suites:
  - name: kuber-master
    run_list:
      - recipe[kubernete_deploy::master]
    driver:
      vm_hostname: kuber-master.dereck.com
    network:
        - ["hostonly", { ip: "192.168.10.21"}]

    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:

  - name: kuber-node
    run_list:
      - recipe[kubernete_deploy::node]
    driver:
      vm_hostname: kuber-node1.dereck.com
    network:
        - ["hostonly", { ip: "192.168.10.21"}]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
