Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "bento/centos-7.3"
  c.vm.hostname = "master-centos-73"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.synced_folder "/root/.kitchen/cache", "/tmp/omnibus/cache", create: true
  c.vm.provider :virtualbox do |p|
  end
end
